apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchserve
spec:
  replicas: 2
  selector:
    matchLabels:
      name: torchserve-elb
  template:
    metadata:
      labels:
        name: torchserve-elb
    spec:
      containers:
        - name: torchserve-app
          image: 466956024587.dkr.ecr.eu-west-1.amazonaws.com/torchserve:latest
          ports:
            - containerPort: 5000