apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchserve
spec:
  replicas: 1
  selector:
    matchLabels:
      name: torchserve-elb
  template:
    metadata:
      labels:
        name: torchserve-elb
    spec:
      containers:
        - name: torchserve-app
          image: 466956024587.dkr.ecr.eu-west-1.amazonaws.com/torchserve:latest
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi
spec:
  restartPolicy: OnFailure
  containers:
  - name: nvidia-smi
    image: nvidia/cuda:latest
    args:
    - "nvidia-smi"
    resources:
      limits:
        nvidia.com/gpu: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values:
              - g4dn.xlarge