apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchserve-deployment-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      name: torchserve-elb
  template:
    metadata:
      labels:
        name: torchserve-elb
    spec:
      containers:
        - name: torchserve-app
          image: 814594265042.dkr.ecr.us-east-2.amazonaws.com/torchserve-repo:latest

          ports:
       
          - containerPort: 9001
            name: inference
            protocol: TCP

          - containerPort: 9002
            name: management
            protocol: TCP

          - containerPort: 9003
            name: metrics
            protocol: TCP

          - containerPort: 7000
            name: grpc-inference
            protocol: TCP

          - containerPort: 7001
            name: grpc-management
            protocol: TCP

          - containerPort: 8501
            name: test
            protocol: TCP

          env:
          - name: DP_DISABLE_HEALTHCHECKS
            value: "xids"
          resources:
            requests:
              ephemeral-storage: "2Gi"
            limits:
              nvidia.com/gpu: 1
              ephemeral-storage: "4Gi"

      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                  - g4dn.xlarge