apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hello-kubernetes
  template:
    metadata:
      labels:
        name: hello-kubernetes
    spec:
      containers:
        - name: app
          image: 466956024587.dkr.ecr.eu-west-1.amazonaws.com/torchserve:latest
          ports:
            - containerPort: 5000