apiVersion: v1
kind: Service
metadata:
  name: torchserve-elb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9003
      name: mainport
      protocol: TCP
      
    - port: 9001
      targetPort: 9001
      name: inference-address
      protocol: TCP

    - port: 9002
      targetPort: 9002
      name: management-address
      protocol: TCP


    - port: 7000
      targetPort: 7000
      name: grpc-inference-port
      protocol: TCP

    - port: 7001
      targetPort: 7001
      name: grpc-management-port
      protocol: TCP

    - port: 8501
      targetPort: 8501
      name: test
      protocol: TCP

  selector:
    name:  torchserve-elb